/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Fajar
 */
public class GambarButton extends javax.swing.JFrame {

    /**
     * Creates new form GambarButton
     */
    public GambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gambar = new javax.swing.JPanel();
        dilucbtn = new javax.swing.JButton();
        razorbtn = new javax.swing.JButton();
        zhongbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        imagepanel = new javax.swing.JPanel();
        Diluc = new javax.swing.JLabel();
        Razor = new javax.swing.JLabel();
        Zhongli = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dilucbtn.setText("Diluc");
        dilucbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dilucbtnActionPerformed(evt);
            }
        });

        razorbtn.setText("Razor");
        razorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razorbtnActionPerformed(evt);
            }
        });

        zhongbtn.setText("Zhongli");
        zhongbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zhongbtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gambarLayout = new javax.swing.GroupLayout(gambar);
        gambar.setLayout(gambarLayout);
        gambarLayout.setHorizontalGroup(
            gambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(dilucbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(razorbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(zhongbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        gambarLayout.setVerticalGroup(
            gambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gambarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dilucbtn)
                    .addComponent(razorbtn)
                    .addComponent(zhongbtn)
                    .addComponent(exitbtn))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(gambar, java.awt.BorderLayout.PAGE_START);

        imagepanel.setLayout(new java.awt.CardLayout());

        Diluc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Diluc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Diluc.jpg"))); // NOI18N
        imagepanel.add(Diluc, "0");

        Razor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Razor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Razor.jpg"))); // NOI18N
        imagepanel.add(Razor, "1");

        Zhongli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Zhongli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Zhongli.png"))); // NOI18N
        imagepanel.add(Zhongli, "2");

        getContentPane().add(imagepanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dilucbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dilucbtnActionPerformed
        CardLayout cl = (CardLayout) (imagepanel.getLayout());
        cl.show(imagepanel,"0");
    }//GEN-LAST:event_dilucbtnActionPerformed

    private void razorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razorbtnActionPerformed
       CardLayout cl = (CardLayout) (imagepanel.getLayout());
       cl.show(imagepanel,"1");
    }//GEN-LAST:event_razorbtnActionPerformed

    private void zhongbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zhongbtnActionPerformed
        CardLayout cl = (CardLayout) (imagepanel.getLayout());
        cl.show(imagepanel,"2");
    }//GEN-LAST:event_zhongbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Diluc;
    private javax.swing.JLabel Razor;
    private javax.swing.JLabel Zhongli;
    private javax.swing.JButton dilucbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JPanel gambar;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JButton razorbtn;
    private javax.swing.JButton zhongbtn;
    // End of variables declaration//GEN-END:variables
}
